name: ludo_app
description: "Ludo app - A modern multiplayer Ludo game with payment integration."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  # Core Flutter packages
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.1

  # Game engine and audio
  flame: ^1.16.0
  flame_audio: ^2.1.8

  # Firebase core (required field fixed)
  firebase_core: ^3.8.0

  # State management
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Lints for code quality
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/Icons/

  fonts:
    - family: Host_Grotesk
      fonts:
        - asset: assets/Fonts/Host_Grotesk/HostGrotesk-VariableFont_wght.ttf
        - asset: assets/Fonts/Host_Grotesk/HostGrotesk-Italic-VariableFont_wght.ttf
          style: italic
        - asset: assets/Fonts/Host_Grotesk/static/HostGrotesk-ExtraBold.ttf
          weight: 700
    - family: Roboto
      fonts:
        - asset: assets/Fonts/Roboto/Roboto-VariableFont_wdth,wght.ttf
