// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUr6tnutUbC1cRbyyd48pYgQjpIfUSGv0',
    appId: '1:882981665935:web:64c735ce16ca67fa1d44fa',
    messagingSenderId: '882981665935',
    projectId: 'ludo-app-5f255',
    authDomain: 'ludo-app-5f255.firebaseapp.com',
    storageBucket: 'ludo-app-5f255.firebasestorage.app',
    measurementId: 'G-WP2PYY8T8B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlghRpJk1VsOS0WMJBRyb_CL4DahwvnVA',
    appId: '1:882981665935:android:73081ad09fb87efc1d44fa',
    messagingSenderId: '882981665935',
    projectId: 'ludo-app-5f255',
    storageBucket: 'ludo-app-5f255.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArJPUUBi9wIbM6vLolDNzWKVoUxeGOXO8',
    appId: '1:882981665935:ios:fe5074849aec24661d44fa',
    messagingSenderId: '882981665935',
    projectId: 'ludo-app-5f255',
    storageBucket: 'ludo-app-5f255.firebasestorage.app',
    iosBundleId: 'com.example.intern1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArJPUUBi9wIbM6vLolDNzWKVoUxeGOXO8',
    appId: '1:882981665935:ios:fe5074849aec24661d44fa',
    messagingSenderId: '882981665935',
    projectId: 'ludo-app-5f255',
    storageBucket: 'ludo-app-5f255.firebasestorage.app',
    iosBundleId: 'com.example.intern1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUr6tnutUbC1cRbyyd48pYgQjpIfUSGv0',
    appId: '1:882981665935:web:4f7f1e19121310121d44fa',
    messagingSenderId: '882981665935',
    projectId: 'ludo-app-5f255',
    authDomain: 'ludo-app-5f255.firebaseapp.com',
    storageBucket: 'ludo-app-5f255.firebasestorage.app',
    measurementId: 'G-7TMK4QTYRM',
  );
}
